// Jenkinsfile
@Library('even-or-odd') _

easyPipeline {
   branch = master
   scmUrl = 'ssh://git@myScmServer.com/repos/myRepo.git'
   email = 'foo@example.com'
   serverPort = '8080'

   osConfiguration = [OS_VERSION: "22.04", DIR_TYPE: "I don't know"]
}
